name: Build Push and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read  
env:  
  AWS_REGION: us-east-1
  AWS_ROLE: ${{ secrets.AWS_ACTION_ROLE }}
  ECR_REPO_NAME: dev
  IMAGE_TAG: ${{ github.run_number }}

jobs: 
  Build:
    runs-on: ubuntu-latest # GitHub  shared runner
    steps:
     - name: clone repo
       uses: actions/checkout@v3
     - name: AWS cred config
       uses: aws-actions/configure-aws-credentials@v4
       with:
          role-to-assume: ${{ env.AWS_ROLE }} # OIDC (open ID connect)
          aws-region: ${{ env.AWS_REGION }}  
     - name: login to ecr  
       uses: aws-actions/amazon-ecr-login@v1 
       id: ecr-login
     - name: Build and tag image 
       id: build-and-push
       run: |
          docker build -t ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPO_NAME}}:${{env.IMAGE_TAG}} .
          
      
     - name: scan docker Image for vulnerabilities 
       uses: aquasecurity/trivy-action@master
       with:
          image-ref: ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPO_NAME}}:${{env.IMAGE_TAG}}
          format: "table"
          severity: "CRITICAL,HIGH"
          exit-code: "1"
          ignore-unfixed: true
     - name: push image to ecr
       run: |          
         docker push ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPO_NAME}}:${{env.IMAGE_TAG}}   

        
     
